#development: &default
#  host: 'http://localhost:9200/'
#  transport_options:
#    request:
#      timeout: !!integer 300
#test:
#  <<: *default
#staging:
#  <<: *default
#production:
#  host: 'http://0000000/'
#  transport_options:
#    request:
#      timeout: !!integer 300